- op: add
  path: /metadata/annotations/argocd.argoproj.io~1sync-wave
  value: "0"
- op: add
  path: /metadata/annotations/gethomepage.dev~1description
  value: Personal knowledge and productivity application
- op: add
  path: /metadata/annotations/gethomepage.dev~1enabled
  value: "true"
- op: add
  path: /metadata/annotations/gethomepage.dev~1group
  value: Applications
- op: add
  path: /metadata/annotations/gethomepage.dev~1href
  value: https://thoughty.swirlit.dev
- op: add
  path: /metadata/annotations/gethomepage.dev~1icon
  value: mdi-lightbulb-on-outline
- op: add
  path: /metadata/annotations/gethomepage.dev~1name
  value: Thoughty
- op: add
  path: /metadata/annotations/gethomepage.dev~1pod-selector
  value: app=thoughty-web
- op: replace
  path: /spec/tls/0/hosts/0
  value: thoughty.swirlit.dev
- op: replace
  path: /spec/tls/0/secretName
  value: swirlit-dev-tls
- op: replace
  path: /spec/rules/0/host
  value: thoughty.swirlit.dev
