apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
  - ../../base
  - external-secrets.yaml
  - database-setup-job.yaml
  - migration-job.yaml
  - network-policy.yaml
  - observability.yaml
  - registry-credentials.yaml
  - ingress-middleware.yaml
components:
  - ../../components/worker
patches:
  - path: configmap-patch.yaml
  - path: server-patch.yaml
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: thoughty-ingress
  - path: api-ingress-patch.yaml
    target:
      kind: Ingress
      name: thoughty-api-ingress
  - path: postgres-backup-patch.yaml
  - path: web-patch.yaml
  - path: worker-patch.yaml
  - path: worker-sync-wave-patch.yaml
images:
  - name: thoughty-server
    newName: registry.swirlit.dev/swirlit/thoughty/thoughty-server
    newTag: 1.6.1
  - name: thoughty-web
    newName: registry.swirlit.dev/swirlit/thoughty/thoughty-web
    newTag: 1.6.1
  - name: postgres
    newName: docker.io/library/postgres
    newTag: 18.6-bookworm
    digest: sha256:b939b3851e2cccb017dc4497af63b15e34efa57fba036548773c53b2f16a8871
