apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thoughty-registry-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: thoughty-registry-auth
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: >-
          {"auths":{"{{ .registry }}":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    - secretKey: registry
      remoteRef:
        key: apps/thoughty/registry
        property: registry
    - secretKey: username
      remoteRef:
        key: apps/thoughty/registry
        property: username
    - secretKey: password
      remoteRef:
        key: apps/thoughty/registry
        property: password
