sonar.projectKey=swirlit:thoughty
sonar.projectName=Thoughty
sonar.sourceEncoding=UTF-8
sonar.sources=thoughty-server/src,thoughty-server/scripts,thoughty-web/src
sonar.tests=thoughty-server/test,thoughty-web/e2e
sonar.javascript.lcov.reportPaths=thoughty-server/coverage/lcov.info,thoughty-web/coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.config.ts,**/*.spec.ts,**/*.test.ts
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.coverage.exclusions=**/main.ts,**/*.module.ts,thoughty-web/src/main.tsx
sonar.scm.provider=git
