apiVersion: v1
kind: ConfigMap
metadata:
  name: thoughty-config
  namespace: thoughty
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  POSTGRES_HOST: postgres.swirlit.internal
  REDIS_HOST: redis.swirlit.internal
  CORS_ORIGIN: https://thoughty.swirlit.dev
  FRONTEND_URL: https://thoughty.swirlit.dev
  KEYCLOAK_ISSUER: https://keycloak.swirlit.dev/auth/realms/swirlit
  KEYCLOAK_JWKS_URI: http://keycloak.swirlit.internal:8080/auth/realms/swirlit/protocol/openid-connect/certs
  KEYCLOAK_AUDIENCE: oauth2-proxy
