apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thoughty-db-admin
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: thoughty-db-admin
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_ADMIN_USER
      remoteRef:
        key: infra/postgres
        property: username
    - secretKey: POSTGRES_ADMIN_PASSWORD
      remoteRef:
        key: infra/postgres
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thoughty-database
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: thoughty-database
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/thoughty/database
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thoughty-app
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: thoughty-app
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/thoughty/app
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thoughty-backup
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: thoughty-backup
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: apps/thoughty/backup
