- op: replace
  path: /spec/routes/0/match
  value: Host(`thoughty.swirlit.dev`) && (Path(`/api`) || PathPrefix(`/api/`)) && Header(`X-Thoughty-Canary`, `always`)
- op: replace
  path: /spec/routes/1/match
  value: Host(`thoughty.swirlit.dev`) && (Path(`/api`) || PathPrefix(`/api/`))
- op: replace
  path: /spec/routes/2/match
  value: Host(`thoughty.swirlit.dev`) && Header(`X-Thoughty-Canary`, `always`)
- op: replace
  path: /spec/routes/3/match
  value: Host(`thoughty.swirlit.dev`)
- op: replace
  path: /spec/tls/secretName
  value: swirlit-dev-tls
- op: add
  path: /spec/routes/0/middlewares/0
  value:
    name: thoughty-sso
- op: add
  path: /spec/routes/1/middlewares/0
  value:
    name: thoughty-sso
