apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: application
resources:
  - ../../deployments
  - external-secrets.yaml
patches:
  - path: configmap-patch.yaml
  - path: server-patch.yaml
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: thoughty-ingress
  - path: postgres-backup-patch.yaml
