apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thoughty
resources:
  - namespace.yaml
  - ../../base
  - postgres.yaml
  - redis.yaml
  - service-accounts.yaml
components:
  - ../../components/worker
