apiVersion: v1
kind: ServiceAccount
metadata:
  name: thoughty-server
  namespace: thoughty
  labels:
    app: thoughty-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thoughty-postgres
  namespace: thoughty
  labels:
    app: postgres
