apiVersion: apps/v1
kind: Deployment
metadata:
  name: thoughty-server-canary
  namespace: thoughty
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: null
        vault.hashicorp.com/role: null
        vault.hashicorp.com/agent-inject-secret-database: null
        vault.hashicorp.com/agent-inject-template-database: null
        vault.hashicorp.com/agent-inject-secret-app: null
        vault.hashicorp.com/agent-inject-template-app: null
    spec:
      serviceAccountName: default
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: thoughty-server
          command: null
          args: null
          envFrom:
            - configMapRef:
                name: thoughty-config
            - secretRef:
                name: thoughty-database
            - secretRef:
                name: thoughty-app
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
