apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
components:
  - ../../components/canary
patches:
  - path: canary-server-patch.yaml
  - path: canary-ingress-patch.yaml
    target:
      kind: Ingress
      name: thoughty-canary-ingress
